### ISSUE TITLE
Deduplication opportunity

### ISSUE THREAD

**Issue by ndrwrbgs** [stakx/AsyncInterceptor#11]
Can we deduplicate effort and merge with https://github.com/JSkimming/Castle.Core.AsyncInterceptor?

**Comment by ndrwrbgs** [comment]
Ah, I see this forked during my hiatus from https://github.com/JSkimming/Castle.Core.AsyncInterceptor/issues/60
:-/ now I don't know what packages are good to use and will be the future. I guess time will tell. Hopefully Castle gives first class support someday :)

**Comment by stakx** [comment]
@ndrwrbgs, development over at Castle.Core has been somewhat slow lately, so I'm not sure that async support will be added there anytime soon. I would claim that my package has an API that conceptually fits very well with DynamicProxy's... but really, use whichever package you prefer.
